train_selfsup_6cams:
    name: [Ouroboros]
    path: [/media/hjx/dataset/DDAD/ddad_train_val/ddad.json]
    split: [train]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 8
    context: [-1,1]
    labels: [depth, 'pose']
    cameras: [[1],[5],[6],[7],[8],[9]]
    depth_type: [lidar]
    repeat: [1]
validation_6cams:
    name: [Ouroboros]
    path: [/media/hjx/dataset/DDAD/ddad_train_val/ddad.json]
    split: [val]
    augmentation:
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 8
    context: []
    labels: [depth]
    cameras: [[1],[5],[6],[7],[8],[9]]
    depth_type: [lidar]


