wrapper:
    recipe: wrapper|default
    max_epochs: 30
    validate_first: False
arch:
    model:
        file: depth/FSMModel
    networks:
        depth:
            recipe: networks/focal_depth_res_net|fsm_ddad
            depth_range: [0.1,100.0]
        pose:
            recipe: networks/conv_pose_net|default
    losses:
        reprojection:
            recipe: losses/reprojection|default
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    depth:
        recipe: evaluation/depth|ddad_resize
optimizers:
    depth:
        recipe: optimizers|adam_20_05
    pose:
        recipe: optimizers|adam_20_05
datasets:
    train:
        recipe: datasets/ddad|train_selfsup_6cams
        dataloader:
            batch_size: 8
    validation:
        recipe: datasets/ddad|validation_6cams
# wandb:
#     recipe: wandb|default
checkpoint:
    recipe: checkpoint|default_local
save:
    recipe: save|depth_splitname